### ISSUE TITLE
Nuxt dies in dev mode after using `createError`

### ISSUE THREAD

**Issue by Perdolique** [pi0/nitro-cloudflare-dev#30]
I've tried to run `throw createError()` inside `server/api/test.ts` and Nuxt died after the `/api/test` request. I suspect it's happening because of incorrect `event` handling by this plugin because removing `nitro-cloudflare-dev` from `modules` helps.

**Comment by pi0** [comment]
Should be fixed in [v0.1.6](https://github.com/pi0/nitro-cloudflare-dev/releases/tag/v0.1.6)
