### ISSUE TITLE
Make persist_dir configurable

### ISSUE THREAD

**Issue by georgobermayr** [pi0/nitro-cloudflare-dev#7]
Right now the persist directory is hardwired to `.wrangler/state/v3 `. It should be made configurable to allow for shared directories with other Cloudflare repos that use the same locally persistent data. 

Workaround: A symlink works fine.

**Comment by miaobuao** [comment]
+1

**Comment by pi0** [comment]
PR is welcome 🙏

**Comment by pi0** [comment]
Will be supported in next release.
